version: "3.1"
services:
  db:
    container_name: mssql
    image: microsoft/mssql-server-linux
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "xihdG!8uNCavA!Rw"
    ports: 
      - 1433:1433